FROM quay.io/ncigdc/gatk3:nightly-2016-02-25-gf39d340
LABEL maintainer="sli6@uchicago.edu"
LABEL version="1.4"
LABEL description="Python wrapper of multithreading `MuTect2` in GATK3 nightly-2016-02-25-gf39d340."

ADD multi_mutect2.py /opt/